config/routes.rb
Rails.application.routes.draw do
  root to: 'workouts#index'

  devise_for :users

  resources :workouts,
            only: [:index, :show, :new, :create]
  resources :routines,
            only: [:index, :show, :new, :edit, :create, :update, :destroy]
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  validates :title, :focus, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :intensity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]

  # GET /routines
  def index
    @routines = Routine.all
  end

  # GET /routines/1
  def show
  end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
  end

  # POST /routines
  def create
    @routine = Routine.new(routine_params)

    if @routine.save
      redirect_to @routine, notice: 'Routine was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /routines/1
  def update
    if @routine.update(routine_params)
      redirect_to @routine, notice: 'Routine was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /routines/1
  def destroy
    @routine.destroy
    redirect_to routines_url, notice: 'Routine was successfully destroyed.'
  end

  private
    def set_routine
      @routine = Routine.find(params[:id])
    end

    def routine_params
      params.require(:routine)
        .permit(:title, :focus, :details)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.paginate(page: params[:page], per_page: 5)
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout, notice: 'Workout was successfully created.'
    else
      render 'new'
    end
  end

  private

  def workout_params
    params.require(:workout)
      .permit(:intensity, :weekday, :workout_log)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/routines/_form.html.erb
<%= simple_form_for(@routine) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :focus %>
    <%= f.input :details %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/routines/edit.html.erb
<h1>Editing Routine</h1>

<%= render 'form' %>

<%= link_to 'Show', @routine %> |
<%= link_to 'Back', routines_path %>

app/views/routines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routines</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routines.each do |routine| %>
      <tr>
        <td><%= link_to 'Show', routine %></td>
        <td><%= link_to 'Edit', edit_routine_path(routine) %></td>
        <td><%= link_to 'Destroy', routine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Routine', new_routine_path %>

app/views/routines/new.html.erb
<h1>New Routine</h1>

<%= render 'form' %>

<%= link_to 'Back', routines_path %>

app/views/routines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_routine_path(@routine) %> |
<%= link_to 'Back', routines_path %>

app/views/workouts/_form.html.erb
<%= simple_form_for @workout do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :intensity %>
    <%= f.input :weekday %>
    <%= f.input :workout_log %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All workouts</h1>

<%= will_paginate @workouts %>

<ul class="workouts">
  <% @workouts.each do |workout| %>
    <li>
      <%= link_to workout.weekday, workout %>
      <li>intensity: <%= workout.intensity %></li>
    </li></br>
  <% end %>
</ul>

<%= will_paginate @workouts %>

<br>

<%= button_to 'New workout', new_workout_path, method: :get %>

<br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to 'Show', workout %></td>
<%
=begin %>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%
=end %>
      </tr>
    <% end %>
  </tbody>
</table>

</br>

<%= link_to 'New Routine', new_routine_path %>

</br>

<% if user_signed_in? %>
  <li><%= link_to current_user.email, edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/workouts/new.html.erb
<h2>Create a new workout!</h2>
<%= render 'form' %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section>
      <% if @workout.weekday? %>
        <h1><%= @workout.weekday %></h1>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @workout.workout_log? %>
      <h3>Log Notes: <%= @workout.workout_log %></h3>
    <% end %>
  </div>
</div>

<%
=begin %>
<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%
=end %>
<%= link_to 'Back', workouts_path %>